' UML da classe Musica com herança de Conteudo

@startuml "Musica class"
skinparam classAttributeIconSize 0
hide circle

abstract class Conteudo {
  -{static} contador: int = 0
  #id: int
  #titulo: String
  #duracaoSegundos: int
  -reproducoes: int
  --
  +Conteudo(titulo: String, duracaoSegundos: int)
  +{static} getProximoId(): int
  +getId(): int
  #setId(id: int): void
  +getTitulo(): String
  +setTitulo(titulo: String): void
  +getDuracaoSegundos(): int
  +getReproducoes(): int
  +setDuracaoSegundos(duracaoSegundos: int): void
  +getCreditos(): String
  +reproduzir(): void
  +getDuracaoFormatada(): String
  +toString(): String
}

class Musica extends Conteudo {
  -album: String
  -artista: String
  --
  +Musica(titulo: String, artista: String, duracaoSegundos: int)
  +Musica(titulo: String, artista: String, album: String, duracaoSegundos: int)
  +getAlbum(): String
  +setAlbum(album: String): void
  +getArtista(): String
  +setArtista(artista: String): void
  +getCreditos(): String
  +toString(): String
}

@enduml